export default [
  { name: 'Jessica Alba', initials: 'J.A.', hint1: 'female', hint2: 'Dark Angel' },
  { name: 'Jennifer Aniston', initials: 'J.A.', hint1: 'female', hint2: 'Friend' },
  { name: 'Sandra Bullock', initials: 'S.B.', hint1: 'female', hint2: 'Speed' },
  { name: 'Tom Cruise', initials: 'T.C.', hint1: 'male', hint2: 'Mission' },
  { name: 'Cameron Diaz', initials: 'C.D.', hint1: 'female', hint2: 'Mary' },
  { name: 'Leonardo Dicaprio', initials: 'L.D.', hint1: 'male', hint2: 'Boat' },
  { name: 'Robert Downey Jr', initials: 'R.D.J.', hint1: 'male', hint2: 'Avenger' },
  { name: 'Morgan Freeman', initials: 'M.F.', hint1: 'male', hint2: '7' },
  { name: 'Tom Hanks', initials: 'T.H.', hint1: 'male', hint2: 'Volleyball' },
  { name: 'Chris Hemsworth', initials: 'C.H.', hint1: 'male', hint2: 'Avenger' },
  { name: 'Hugh Jackman', initials: 'H.J.', hint1: 'male', hint2: 'X-Men' },
  { name: 'Angelina Jolie', initials: 'A.J.', hint1: 'female', hint2: 'Wanted' },
  { name: 'Nicole Kidman', initials: 'N.K.', hint1: 'female', hint2: 'Moulin Rouge' },
  { name: 'Zachary Levi', initials: 'Z.L.', hint1: 'male', hint2: 'Chuck' },
  { name: 'Lindsay Lohan', initials: 'L.L.', hint1: 'female', hint2: 'Mean Girl' },
  { name: 'Edward Norton', initials: 'E.N.', hint1: 'male', hint2: 'Fight Club' },
  { name: 'Brad Pitt', initials: 'B.P.', hint1: 'male', hint2: 'Fight Club' },
  { name: 'Keanu Reeves', initials: 'K.R.', hint1: 'male', hint2: 'Neo' },
  { name: 'Will Smith', initials: 'W.S.', hint1: 'male', hint2: 'Bel-Air' },
  { name: 'Denzel Washington', initials: 'D.W.', hint1: 'male', hint2: 'Hurricane' },
];
