export default [
  { name: 'Garth Brooks', initials: 'G.B.', hint1: 'male', hint2: 'Country' },
  { name: 'Mariah Carey', initials: 'M.C.', hint1: 'female', hint2: 'Pop' },
  { name: 'Johnny Cash', initials: 'J.C.', hint1: 'male', hint2: 'Country' },
  { name: 'Ray Charles', initials: 'R.C.', hint1: 'male', hint2: 'R&B' },
  { name: 'Bob Dylan', initials: 'B.D.', hint1: 'male', hint2: 'Folk' },
  { name: 'Hilary Duff', initials: 'H.D.', hint1: 'female', hint2: 'Pop' },
  { name: 'Aretha Franklin', initials: 'A.F.', hint1: 'female', hint2: 'R&B' },
  { name: 'Lady Gaga', initials: 'L.G.', hint1: 'female', hint2: 'Pop' },
  { name: 'Whitney Houston', initials: 'W.H.', hint1: 'female', hint2: 'Bodyguard' },
  { name: 'Michael Jackson', initials: 'M.J.', hint1: 'male', hint2: 'Pop' },
  { name: 'Beyonce Knowles', initials: 'B.K.', hint1: 'female', hint2: 'Destiny' },
  { name: 'Madonna', initials: 'M.', hint1: 'female', hint2: 'Pop' },
  { name: 'Bob Marley', initials: 'B.M.', hint1: 'male', hint2: 'Reggae' },
  { name: 'Dolly Parton', initials: 'D.P.', hint1: 'female', hint2: 'Country' },
  { name: 'Elvis Presley', initials: 'E.P.', hint1: 'male', hint2: 'Blue shoes' },
  { name: 'Taylor Swift', initials: 'T.S.', hint1: 'female', hint2: 'Pop' },
  { name: 'Justin Timberlake', initials: 'J.T.', hint1: 'male', hint2: 'Pop' },
  { name: 'Shania Twain', initials: 'S.T.', hint1: 'female', hint2: 'Country' },
  { name: 'Stevie Wonder', initials: 'S.W.', hint1: 'male', hint2: 'R&B' },
  { name: 'Jay Z', initials: 'J.Z.', hint1: 'male', hint2: 'Shoulder Dirt' },
];
