export default [
  { name: 'Larry Bird', initials: 'L.B.', hint1: 'retired', hint2: 'Celtics' },
  { name: 'Kobe Bryant', initials: 'K.B.', hint1: 'retired', hint2: 'Lakers' },
  { name: 'Steph Curry', initials: 'S.C.', hint1: 'active', hint2: 'Warriors' },
  { name: 'Tim Duncan', initials: 'T.D.', hint1: 'retired', hint2: 'Spurs' },
  { name: 'Kevin Durant', initials: 'K.D.', hint1: 'active', hint2: 'Nets' },
  { name: 'Horace Grant', initials: 'H.G.', hint1: 'retired', hint2: 'Bulls' },
  { name: 'James Harden', initials: 'J.H.', hint1: 'active', hint2: 'Rockets' },
  { name: 'Lebron James', initials: 'L.J.', hint1: 'active', hint2: 'Lakers' },
  { name: 'Magic Johnson', initials: 'M.J.', hint1: 'retired', hint2: 'Lakers' },
  { name: 'Michael Jordan', initials: 'M.J.', hint1: 'retired', hint2: 'Bulls' },
  { name: 'Scottie Pippen', initials: 'S.P.', hint1: 'retired', hint2: 'Bulls' },
  { name: 'Dennis Rodman', initials: 'D.R.', hint1: 'retired', hint2: 'Pistons' },
  { name: 'Klay Thompson', initials: 'K.T.', hint1: 'active', hint2: 'Warriors' },
  { name: 'Dwayne Wade', initials: 'D.W.', hint1: 'retired', hint2: 'Heat' },
];
